export const aliases = Object.fromEntries(Object.entries({
"Alice à la mode": "Alice à la mode ¨ Masanori Akita",
"aterlbus": "αterlβus ¨ Aoi",
"αterlβus": "αterlβus ¨ Aoi",
"［X］": "[X] ¨ Blacklolita",
"[X]": "[X] ¨ Blacklolita",
"DX超性能フルメタル少女": "DX Choseinou Full Metal Shojo ¨ IOSYS TRAX (uno with.ちよこ)",
"GLORY：ROAD": "GLORY：ROAD ¨ uma vs. モリモリあつし",
"II": "͟͝͞Ⅱ́̕ ¨ Cytus",
"Ⅱ": "͟͝͞Ⅱ́̕ ¨ Cytus",
"͟͝͞Ⅱ́̕": "͟͝͞Ⅱ́̕ ¨ Cytus",
"LIVHT MY W​Δ​Y": "LIVHT MY WΔY ¨ かめりあ feat. STΔRLIVHT",
"nέο κόsmo": "nέo κósmo ¨ ak+q × Street",
"nέo κόsmo": "nέo κósmo ¨ ak+q × Street",
"vsキミ戦争": "Romance Wars ¨ U-ske (feat. lueur)",
"yuardina": "γuarδina ¨ Aoi",
"guardina": "γuarδina ¨ Aoi",
"γuarδina": "γuarδina ¨ Aoi",
"アリス・リデルに捧ぐ": "To: Alice Liddell ¨ モリモリあつし",
"アローンアンドローン": "Alone ＆ Lorn ¨ Ponchi♪ feat.はぁち",
"クロートーと星の観測者": "Clotho and the stargazer ¨ しーけー",
"コスモポップファンクラブ": "Cosmo Pop Funclub ¨ ナユタン星人",
"だいあるのーと": "Dialnote ¨ 七草クリむ",
"ネコノテ・カリタガール": "Dancin' on a Cat's Paw ¨ Ino(chronoize)",
"ハルトピア ~Utopia of Spring~": "Harutopia ~Utopia of Spring~ ¨ A-zu-ra",
"ピコPico*とらんすれーしょんっ！": "PICO-Pico-Translation! ¨ t+pazolite,ななひら,Cranky,Pico*",
"フライブルクとエンドロウル": "Flyburg and Endroll ¨ アリスシャッハと魔法の楽団",
"ベースラインやってる？w": "Can I Friend You on Bassbook? Lol ¨ かめりあ feat. ななひら",
"レイヴンズ・プライド": "Raven's Pride ¨ みーに feat. はらもりよしな",
"不浄な白い鳥": "Impure Bird ¨ MIssionary",
"九番目の迷路": "Maze No.9 ¨ アリスシャッハと魔法の楽団",
"光": "Hikari ¨ THB",
"光速神授説 - Divine Light of Myriad -": "Divine Light of Myriad ¨ yoho",
"四月の雨": "April showers ¨ cubesato",
"堕楽の園": "Illegal Paradise ¨ gmtn. (witch's slave)",
"夜桜吹雪": "Yosakura Fubuki ¨ A.SAKA",
"妖艶魔女 -trappola bewitching-": "trappola bewitching ¨ gmtn.",
"彩る夏の恋花火": "Summer Fireworks of Love ¨ karatoPαnchii feat. はるの",
"秋の陽炎": "Haze of Autumn ¨ karatoPαnchii feat. はるの",
"彼方の夢へと": "To the Furthest Dream ¨ ii/night feat. 綺良雪",
"心": "Heart ¨ 削除 (Violin : Katali)",
"怒槌": "Ikazuchi ¨ 光吉猛修",
"患部で止まってすぐ溶ける　～ 狂気の優曇華院": "Kanbu de Tomatte Sugu Tokeru ¨ ARM＋夕野ヨシミ (IOSYS) feat. miko",
"感情の摩天楼 ～Arr.Demetori": "Kanjou no Matenrou ～Arr.Demetori ¨ Demetori",
"月に叢雲華に風": "Tsuki ni Murakumo, Hana ni Kaze ¨ 幽閉サテライト",
"業 -善なる神と この世の悪について-": "Misdeed -la bonté de Dieu et l'origine du mal- ¨ 光吉猛修 vs 穴山大輔",
"業 -善なる神とこの世の悪について-": "Misdeed -la bonté de Dieu et l'origine du mal- ¨ 光吉猛修 vs 穴山大輔",
"烈華RESONANCE": "REKKA RESONANCE ¨ REDALiCE vs Kobaryo",
"無機質世界に彩を": "Redraw the Colorless World ¨ MisomyL",
"無法地点": "Lawless Point ¨ La prière",
"狂恋ROMANCE": "KYOREN ROMANCE ¨ REDALiCE vs DJ Myosuke feat. DELUTAYA",
"狂言綺語": "False Embellishment ¨ 影虎。＆ ikaruga_nex",
"白道、多希望羊と信じありく。": "LunarOrbit -believe in the Espebranch road- ¨ Apo11o program ft. 大瀬良あい",
"神奈川電脳暗渠": "Kanagawa Cyber Culvert ¨ 南ゆに",
"竹": "Bamboo ¨ 立秋 feat.ちょこ",
"緋纏いの宵": "Evening in Scarlet ¨ Freezer feat.妃莓",
"緋色月下、狂咲ノ絶 (nayuta 2017 ver.)": "Hiiro Gekka, Kyoushou no Zetsu (nayuta 2017 ver.) ¨ nayuta x 黒鳥(EastNewSound)",
"虚空の夢": "Solitary Dream ¨ ak+q feat. Sennzai",
"蛍火の雪": "Hotarubi no Yuki ¨ Endorfin.",
"蜘蛛の糸": "Spider's Thread ¨ きくお×cosMo＠暴走P feat.影縫英",
"迷える音色は恋の唄": "A Wandering Melody of Love ¨ からとP⍺ոchii少年 feat.はるの",
"雨神楽": "Amekagura ¨ 荒谷サトル",
"魔王": "World Ender ¨ sasakure.UK × TJ.hangneil",
"最強STRONGER": "SAIKYO STRONGER ¨ REDALiCE vs USAO",
"ヒュブリスの頂に聳えるのは": "Hybris (The one who shattered) ¨ qfeileadh feat.のあ"
}).map(([k, v]) => [k, v.split(" ¨ ")]));

export const unaliased = Object.fromEntries([
"#1f1e33 ¨ かめりあ(EDP)",
"〇、 ¨ Kolaa ＆ 熊子",
"1F√ ¨ WHITEFISTS",
"7thSense ¨ 削除",
"99 Glooms ¨ Sta",
"Abstruse Dilemma ¨ Ashrount vs. 打打だいず",
"Aegleseeker ¨ Silentroom vs Frums",
"Ai Drew ¨ Feryquitous",
"AI[UE]OON ¨ MYUKKE.",
"Aleph-0 ¨ LeaF",
"Alexandrite ¨ WAiKURO",
"Alice's Suitcase ¨ Endorfin.",
"Altair (feat. *spiLa*) ¨ kamome sano ＆ you",
"Altale ¨ Sakuzyo",
"AlterAle ¨ Arik Kau Delay (アラ ＆ かゆき ＆ でり)",
"AMAZING MIGHTYYYY!!!! ¨ WAiKURO",
"amygdata ¨ nitro",
"Anökumene ¨ Jun Kuroda",
"Antagonism ¨ Yooh vs. siromaru",
"Antithese ¨ Blacklolita",
"Arcahv ¨ Feryquitous",
"Arcana Eden ¨ Team Grimoire vs Sakuzyo vs Laur",
"Arghena ¨ Feryquitous vs Laur",
"Ascent ¨ TANUKI",
"Astra walkthrough ¨ paraoka",
"Astral tale ¨ Noah",
"AttraqtiA ¨ かめりあ",
"Aurgelmir ¨ 溝口ゆうま feat. 大瀬良あい",
"Auxesia ¨ ginkiha",
"Avant Raze ¨ Sampling Masters MEGA",
"Ävril -Flicka i krans- ¨ Rigël Theatre",
"Awaken In Ruins ¨ Supa7onyz",
"Axium Crisis ¨ ak+q",
"B.B.K.K.B.K.K. ¨ nora2r",
"Babaroque ¨ cYsmix",
"BADTEK ¨ EBIMAYO",
"BATTLE NO.1 ¨ TANO*C Sound Team",
"Be There ¨ PSYQUI",
"Beside You ¨ 江口孝宏",
"Black Lotus ¨ wa.",
"Black Territory ¨ DJ Myosuke",
"Blaster ¨ Massive New Krew",
"Blocked Library ¨ 影虎。",
"Blossoms ¨ T2Kazuya",
"BLRINK ¨ Sta",
"blue comet ¨ ああああ",
"Blue Rose ¨ Cosmograph",
"Bookmaker (2D Version) ¨ Kobaryo",
"Brand new world ¨ U-ske",
"BUCHiGiRE Berserker ¨ REDALiCE vs MASAKI",
"Bullet Waiting for Me (James Landino remix) ¨ Nikki Simmons",
"Call My Name feat. Yukacco ¨ Mameyudoufu",
"Callima Karma ¨ t+pazolite vs Feryquitous",
"Capella ¨ ARForest",
"carmine:scythe ¨ かゆき",
"CHAOS ¨ Æsir",
"Chelsea ¨ 7mai",
"Chronicle ¨ Lime",
"Chronostasis ¨ 黒皇帝",
"Climax ¨ USAO",
"Coastal Highway ¨ Glitch Droids",
"cocoro*cosmetic ¨ KOTONOHOUSE",
"conflict ¨ siromaru + cranky",
"corps-sans-organes ¨ cybermiso",
"Corruption ¨ 3R2",
"Cosmica ¨ Nhato",
"Crimson Throne ¨ Dimier√Lisb",
"CROSS†OVER ¨ HyuN feat. LyuU",
"CROSS†SOUL ¨ HyuN feat. Syepias",
"cry of viyella ¨ Laur",
"Crystal Gravity ¨ Tanchiky vs. siromaru",
"Cyaegha ¨ USAO",
"cyanine ¨ jioyi",
"Cybernecia Catharsis ¨ Tanchiky",
"CYCLES ¨ Masayoshi Minoshima feat. 綾倉盟",
"Dandelion ¨ Farhan",
"Dantalion ¨ Team Grimoire",
"DataErr0r ¨ Cosmograph",
"Dazzle hop ¨ Sampling Masters MEGA",
"DDD ¨ はがね",
"Defection ¨ TeddyLoid feat. DELTA",
"Dement ~after legend~ ¨ Cosmograph",
"Devillic Sphere ¨ 3R2",
"Diode ¨ Kolaa",
"Dot to Dot feat. shully ¨ Mameyudoufu",
"Dreadnought ¨ Mastermind (xi+nora2r)",
"Dream goes on ¨ Tiny Minim",
"Dreamin' Attraction!! ¨ 翡乃イスカ",
"DRG ¨ onoken",
"dropdead ¨ Frums",
"Dynitikós ¨ Prower",
"Eccentric Tale ¨ Yamajet",
"eden ¨ \"漆黒\"の堕天使《Gram》†Versus†\"聖刻\"の熾天使《Gram》",
"Ego Eimi ¨ BlackY feat. Risa Yuzuki",
"Einherjar Joker ¨ DJ Genki vs Gram",
"Empire of Winter ¨ Street",
"enchanted love ¨ linear ring",
"ENERGY SYNERGY MATRIX ¨ Tanchiky",
"Equilibrium ¨ Maozon",
"Essence of Twilight ¨ ak+q",
"Ether Strike ¨ Akira Complex",
"Evoltex (poppi'n mix) ¨ Arch vs n3pu",
"Faint Light (Arcaea Edit) ¨ Taishi",
"Fairytale ¨ chitose",
"Fallensquare ¨ Silentroom",
"FANTA5Y ¨ Moon Jelly ＆ YUKIYANAGI",
"Far Away Light ¨ technoplanet feat. はるの ＆ 黒沢ダイスケ",
"Feels So Right feat. Renko ¨ Mysteka",
"Felis ¨ M2U",
"felys final remix ¨ onoken",
"Filament ¨ Puru",
"Final Step! ¨ Lime",
"First Snow ¨ 黒魔",
"Flashback ¨ ARForest",
"FLUFFY FLASH ¨ Kobaryo",
"Fracture Ray ¨ Sakuzyo",
"Free Myself ¨ lapix feat. mami",
"FREEF4LL ¨ YUKIYANAGI",
"G e n g a o z o ¨ -45",
"Galactic Love ¨ La prière",
"Galaxy Friends ¨ Kobaryo",
"Garakuta Doll Play ¨ t+pazolite",
"Gekka (Short Version) ¨ Nhato",
"Genesis ¨ Iris",
"Genesis ¨ Morrigan feat. Lily",
"GENOCIDER ¨ DJ Myosuke",
"GIMME DA BLOOD ¨ C-Show",
"GIMMICK ¨ Ms.Sill",
"Give Me a Nightmare ¨ アリスシャッハと魔法の楽団",
"Glow ¨ SPACELECTRO",
"goldenslaughterer ¨ zts",
"Good bye, Merry-Go-Round. ¨ Yooh",
"GOODTEK (Arcaea Edit) ¨ EBIMAYO",
"Got hive of Ra ¨ E.G.G.",
"Grievous Lady ¨ Team Grimoire vs Laur",
"Grimheart ¨ Puru",
"Halcyon ¨ xi",
"Hall of Mirrors ¨ Sta",
"Head BONK ache ¨ saaa ft. MC iwata Bros.",
"Heart Jackin' ¨ Yu_Asahina",
"Heavenly caress ¨ Noah",
"Heavensdoor ¨ LeaF",
"HELLOHELL ¨ 暁Records",
"HIVEMIND ¨ かたぎり",
"I've heard it said ¨ Combatplayer",
"Iconoclast ¨ Yamajet",
"Ignotus ¨ ak+q",
"Ignotus Afterburn ¨ Arcaea Sound Team",
"IMPACT ¨ USAO feat. 光吉猛修",
"Infinite Strife, ¨ BlackYooh vs. siromaru",
"Infinity Heaven ¨ HyuN",
"init() ¨ kamome sano",
"inkar-usi ¨ DIA",
"Innocence ¨ Powerless feat. Sennzai",
"INTERNET OVERDOSE ¨ Aiobahn feat. KOTOKO",
"INTERNET YAMERO ¨ Aiobahn feat. KOTOKO",
"IONOSTREAM ¨ Tatsh",
"IZANA ¨ t+pazolite vs P*Light",
"Jingle ¨ DJ Noriken",
"Journey ¨ ARForest",
"Jump ¨ Rasmus Faber",
"Kissing Lucifer ¨ ETIA.",
"La'qryma of the Wasteland ¨ DJ Noriken",
"LAMIA ¨ BlackY",
"Lapis ¨ SHIKI",
"Last ¨ onoken",
"Last | Eternity ¨ onoken",
"Last | Moment ¨ onoken",
"Last Celebration ¨ Laur vs CK",
"lastendconductor ¨ zts",
"Lazy Addiction ¨ sky_delta",
"Let you DIVE! (nitro rmx) ¨ nitro (lowiro)",
"Let's Rock (Arcaea mix) ¨ ikaruga_nex vs FALCHiON",
"Lethaeus ¨ Silentroom",
"Lethal Voltage ¨ siqlo",
"Libertas ¨ Zekk",
"Life is PIANO ¨ Junk",
"Lightning Screw ¨ HiTECH NINJA",
"Lights of Muse ¨ Ayatsugu_Otowa",
"Linear Accelerator ¨ THE SHAFT",
"Live Fast Die Young ¨ anubasu-anubasu",
"Logos ¨ polysha feat. 高域みよ",
"Löschen ¨ BlackY feat. Risa Yuzuki",
"Lost Civilization ¨ Laur vs CK",
"Lost Desire ¨ Powerless feat. Sennzai",
"Lost Emotion feat. nomico ¨ Masayoshi Minoshima(ALR)",
"Lost in the Abyss ¨ FELT",
"Loveless Dress ¨ かねこちはる",
"Lucid Traveler ¨ Akira Complex vs 3R2",
"Lucifer ¨ chitose",
"Lumia ¨ sky_delta",
"Luna Rossa ¨ r0y",
"Macrocosmic Modulation ¨ JAKAZiD",
"Magnolia ¨ M2U Vocal by Guriri",
"MAHOROBA ¨ Zekk",
"Malicious Mischance ¨ s-don",
"Manic Jeer ¨ ルゼ",
"MANTIS (Arcaea Ultra-Bloodrush VIP) ¨ Akira Complex feat. kiraku",
"Masquerade Legion ¨ Srav3R ＆ DJ Noriken",
"MAXRAGE ¨ EBIMAYO",
"Mazy Metroplex ¨ aran",
"Medusa ¨ HiTECH NINJA",
"Memory Forest ¨ ETIA.",
"memoryfactory.lzh ¨ Frums",
"MERLIN ¨ REDALiCE",
"Meta-Mysteria ¨ DJ Noriken",
"Metallic Punisher ¨ INNOCENT NOIZE",
"MIRINAE ¨ TAK × Zekk",
"Mirzam ¨ Aoi vs. siqlo",
"Modelista ¨ HiTECH NINJA",
"Monochrome Princess ¨ polysha",
"Moonheart ¨ 翡乃イスカ",
"Moonlight of Sand Castle ¨ 旅人E",
"MORNINGLOOM ¨ saaa",
"Nameless Passion ¨ 天束 feat.Sennzai",
"NEO WINGS ¨ SOUND HOLIC feat. Nana Takahashi",
"New York Back Raise ¨ saaa + kei_iwata + stuv + わかどり",
"next to you ¨ uma feat. 橘花音",
"Nhelv ¨ Silentroom",
"Nirv lucE ¨ しーけー",
"NULCTRL ¨ Silentroom",
"NULL APOPHENIA ¨ N²",
"Oblivia ¨ Saiph",
"OMAKENO Stroke ¨ t+pazolite",
"On And On!! feat. Jenga ¨ ETIA.",
"One Last Drive ¨ REDSHiFT",
"Oracle ¨ TQ☆",
"Oshama Scramble! ¨ t+pazolite",
"ouroboros -twin stroke of the end- ¨ Cranky VS MASAKI",
"Ouvertüre ¨ USAO ＆ DJ Genki feat. ルーン(CV:河瀬茉希)",
"overdead. ¨ fn",
"Overwhelm ¨ xi",
"Paper Witch ¨ Yu-dachi",
"Paradise ¨ Sound Souler",
"Particle Arts ¨ Virtual Self",
"Party Vinyl ¨ モリモリあつし",
"Pentiment ¨ Nothing But Requiem with Museo",
"Phantasia ¨ Yunosuke",
"PRAGMATISM ¨ Laur",
"PRAGMATISM -RESURRECTION- ¨ Laur",
"Primeval Texture ¨ くるぶっこちゃん",
"PRIMITIVE LIGHTS ¨ TAG",
"Prism ¨ bermei.inazawa ft. Chata",
"Protoflicker ¨ Silentroom",
"PUPA ¨ モリモリあつし",
"Purgatorium ¨ お月さま交響曲",
"Purple Verse ¨ Hommarju",
"Qovat ¨ owl＊tree",
"qualia -ideaesthesia- ¨ nitro",
"Quon ¨ DJ Noriken",
"Quon ¨ Feryquitous",
"Rabbit In The Black Room ¨ Rabbit House",
"REconstruction ¨ Ryazan",
"Red and Blue ¨ Silentroom",
"Red and Blue and Green ¨ fn(ArcaeaSoundTeam)",
"Redolent Shape ¨ Sanaas",
"Reinvent ¨ Sound Souler",
"Relentless ¨ Akira Complex",
"Remind the Souls (Short Version) ¨ Nhato",
"ReviXy ¨ ikaruga_nex",
"RGB ¨ MEMODEMO X AQUASINE",
"Ringed Genesis ¨ Edelritter",
"Rise ¨ Combatplayer",
"Rise of the World ¨ cosMo＠暴走P",
"Rugie ¨ Feryquitous feat. Sennzai",
"SACRIFICE feat. ayame ¨ Masayoshi Minoshima(ALR)",
"Sakura Fubuki ¨ Street",
"san skia ¨ ユアミトス",
"Sayonara Hatsukoi ¨ REDSHiFT",
"Scarlet Cage ¨ Daisuke Kurosawa",
"Scarlet Lance ¨ MASAKI (ZUNTATA)",
"Seclusion ¨ Laur feat. Sennzai",
"Senkyou ¨ MYTK",
"Shades of Light in a Transcendent Realm ¨ ak+q",
"Sheriruth ¨ Team Grimoire",
"Sheriruth (Laur Remix) ¨ Laur",
"Silent Rush ¨ Soleily",
"Singularity ¨ ETIA.",
"Singularity VVVIP ¨ Arcaea Sound Team against ETIA.",
"Small Cloud Sugar Candy ¨ テヅカ x Aoi feat. 桃雛なの",
"Snow White ¨ Puru",
"SOUNDWiTCH ¨ HATE",
"Specta ¨ Junk",
"STAGER (ALL STAGE CLEAR) ¨ Ras",
"Stasis ¨ Maozon",
"Stratoliner ¨ C-Show",
"Strongholds ¨ Yooh",
"Sulfur ¨ ぺのれり",
"Suomi ¨ Aire",
"SUPERNOVA ¨ BACO",
"Surrender ¨ void",
"Syro ¨ Mitomoro",
"syūten ¨ Apo11o\"COLLAPSAR\"program ft. 大瀬良あい",
"Technicolour ¨ Maozon",
"Tempestissimo ¨ t+pazolite",
"TEmPTaTiON ¨ かねこちはる",
"TeraVolt ¨ Katali",
"Teriqma ¨ owl＊tree",
"Testify ¨ void (Mournfinale) feat. 星熊南巫",
"The Formula ¨ Junk",
"The Message ¨ Jun Kuroda",
"The Survivor (Game Edit) ¨ Taishi",
"THE ULTIMACY ¨ Massive New Krew vs aran",
"Tie me down gently ¨ 溝口ゆうま feat. 大瀬良あい",
"Tiferet ¨ xi + Sta",
"To the Milky Way ¨ 黒魔",
"Transient Space ¨ sleepless, Gardens, aspect",
"Trap Crow ¨ Puru",
"Trrricksters!! ¨ s-don vs. 翡乃イスカ",
"Turbocharger ¨ A/I",
"Ultimate taste ¨ ぱらどっと",
"ultradiaxon-N3 ¨ nitro (lowiro)",
"UNKNOWN LEVELS ¨ Yuta Imai",
"Used to be ¨ KIVΛ",
"Valhalla:0 ¨ Juggernaut.",
"Vandalism ¨ Ashrount",
"VECTOЯ ¨ WHITEFISTS",
"Vexaria ¨ ak+q",
"Vicious [ANTi] Heroism ¨ Kobaryo",
"Vicious Heroism ¨ Kobaryo",
"Vindication ¨ Laur",
"Vivid Theory ¨ ak+q",
"Viyella's Tears ¨ Laur",
"WAIT FOR DAWN ¨ U-ske feat. 棗いつき",
"Wish Upon a Snow ¨ 打打だいず",
"with U ¨ t+pazolite ＆ Massive New Krew feat. リリィ(CV:青木志貴)",
"World Fragments III(radio edit) ¨ xi",
"World Vanquisher ¨ void (Mournfinale)",
"world.execute(me); ¨ Mili",
"Xanatos ¨ Tatsh",
"Xeraphinite ¨ BlackY",
"XTREME ¨ USAO",
"Your voice so... feat. Such ¨ PSYQUI",
"μ ¨ Frums",
"ΟΔΥΣΣΕΙΑ ¨ Sober Bear",
"ω4 ¨ 穴山大輔 VS 光吉猛修 VS Kai",
].map(v => v.split(" ¨ ")));